# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 65b9f95b4b1c57a52020597d747f2b462e5894a6c7bba8c1cedc3090e1528e6b0657d1086a0fa874c0655ef31996cd57807c074f9dae56b42a38b52eaaa74508

test:
  secret_key_base: f2ddaa0b2c744ec37aff3aabd77eed27591ce40e9b7a5acbcf953d0eabb929052ff5ffd99f5e1ff07bf3da64e23fb97189ab486b36107d5b75b6d4594f51a2ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
